language: php
php:
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - gulp --production

before_install:
    - npm install -g gulp
    - npm install -g bower

install:
    - composer update
    - npm install
    - bower install


